### ISSUE TITLE
ProblemSolve 페이지 구현

### ISSUE THREAD

**Issue by jjiny0716** [0NYE/FPS-frontend#16]
## Description

- 문제 풀이 페이지를 구현합니다.

## Todo List

- [ ] 문제 풀이 페이지 헤더 구현
- [ ] 문제 id에 해당하는 문제의 제목, 설명, 미리보기 렌더링
- [ ] html, css, js 코드에디터 구현
- [ ] 코드 결과물 실시간 렌더링 및 최종 결과물과 비교
- [ ] 기타 UI(다른 탭, 제출 버튼) 구현
